import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/*
const response = await fetch('/api/ai', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ messages }),
});
const data = await response.json();
console.log(data.result);
*/

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kéméndi Dániel",
  keywords: ["Kéméndi Dániel", "Portfolio", "AI Product Manager"],
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}> 
          {children}
      </body>
    </html>
  );
}
